# Generated by Django 2.2.5 on 2019-11-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20191109_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_rank',
        ),
    ]
