# Generated by Django 2.2.5 on 2019-11-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_datastructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastructure',
            name='community',
        ),
    ]
