# Generated by Django 2.2.5 on 2019-11-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_datastructure_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastructure',
            name='community',
        ),
    ]
