# Generated by Django 2.2.5 on 2019-12-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_remove_datastructure_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='additional_data_structure',
        ),
        migrations.DeleteModel(
            name='DataStructure',
        ),
    ]
