# Generated by Django 2.2.5 on 2019-12-22 07:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0024_communitymembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_object_name', models.CharField(max_length=200)),
                ('post_object_description', models.CharField(max_length=200)),
                ('post_object_tag', models.CharField(max_length=200)),
                ('post_object_creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_fields', django.contrib.postgres.fields.jsonb.JSONField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Post')),
                ('post_object_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
