# Generated by Django 2.2.5 on 2019-11-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_rank',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
