# Generated by Django 2.2.5 on 2019-11-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_community_community_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=100)),
                ('field_isrequired', models.BooleanField(default=False)),
                ('field_dstructure', models.CharField(choices=[('Txt', 'Text'), ('Video', 'Video'), ('Audio', 'Audio'), ('Date', 'Date'), ('Email', 'E-Mail'), ('Int', 'Integer'), ('Dec', 'Decimal'), ('Loc', 'Location'), ('URL', 'URL')], default='Txt', max_length=5)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
            ],
        ),
    ]
