# Generated by Django 2.2.5 on 2019-11-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_datastructure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataStructure',
        ),
    ]
