# Generated by Django 2.2.5 on 2019-11-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_post_additional_data_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
