# Generated by Django 2.2.5 on 2019-12-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_community_community_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
